package com.zaakman.lib.orm;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zaakman.lib.beans.StorageBean;

import com.zaakman.lib.orm.StorageBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig storageBeanDaoConfig;

    private final StorageBeanDao storageBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        storageBeanDaoConfig = daoConfigMap.get(StorageBeanDao.class).clone();
        storageBeanDaoConfig.initIdentityScope(type);

        storageBeanDao = new StorageBeanDao(storageBeanDaoConfig, this);

        registerDao(StorageBean.class, storageBeanDao);
    }
    
    public void clear() {
        storageBeanDaoConfig.clearIdentityScope();
    }

    public StorageBeanDao getStorageBeanDao() {
        return storageBeanDao;
    }

}
